# Generated by Django 2.2.6 on 2019-12-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='NULL', max_length=175)),
                ('link', models.CharField(default='NULL', max_length=175)),
                ('logo', models.ImageField(default='NULL', max_length=1000, upload_to='')),
                ('about', models.CharField(max_length=2000)),
                ('rules', models.CharField(max_length=200)),
                ('link2', models.CharField(default='NULL', max_length=200)),
                ('details', models.CharField(max_length=2000)),
                ('image', models.ImageField(max_length=1000, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=10000, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=400)),
                ('college', models.TextField(max_length=1000)),
                ('department', models.TextField(max_length=1000)),
                ('year', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='sponsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=175)),
                ('image', models.ImageField(max_length=1000, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('fb', models.CharField(max_length=1000)),
                ('post', models.CharField(max_length=100)),
            ],
        ),
    ]
